### ISSUE TITLE
Where to buy screen?

### ISSUE THREAD

**Issue by comejar** [democloid/picoTrackerPortable-pcb#6]
Hi is there a link anywhere for which screen to buy.
The files are a bit confusing it seems like the build document with links to parts is for the none portable version as it links to a 3.2" screen.
Thankyou

**Comment by maks** [comment]
Yes the LCD for the portable version is different from the "desktop" version of the picoTracker.
Here is [a link to the screens](https://www.aliexpress.com/item/4000369488626.html) I've used for my builds of the portable version

**Comment by comejar** [comment]
> Yes the LCD for the portable version is different from the "desktop" version of the picoTracker. Here is [a link to the screens](https://www.aliexpress.com/item/4000369488626.html) I've used for my builds of the portable version

thankyou for the response and link!
